function CreateStockBoxPlot(time, stock, vol, xi, samples, p, alpha, printFig)
%CREATEFIGURE(time,stock,vol,xi)
%  time:  vector of x data
%  stock:  vector of y data
%  vol:  vector of y data
%  xi:  vector of y data

%  Auto-generated by MATLAB on 05-Aug-2008 20:32:58

% Create figure
figure1 = figure('XVisual',...
    '0x24 (TrueColor, depth 24, RGB mask 0xff0000 0xff00 0x00ff)',...
    'Color', 'white');

[n m] = size(stock);
box('on');
hold('all');
subplot(1, 2, 1, 'Parent', figure1);
boxplot([stock(n * 1/5, :)' stock(n * 2/5, :)' stock(n * 3/5, :)' stock(n * 4/5, :)' stock(n, :)'])

% Create title
title('Box whiskers plot of the stock price');

% Create xlabel
xlabel('Time (* 1/5)');

% Create ylabel
ylabel('Stock Price');

box('on');
hold('all');
% Create subplot
subplot1 = subplot(1,2,2,'Parent',figure1);

boxplot([vol(n * 1/5, :)' vol(n * 2/5, :)' vol(n * 3/5, :)' vol(n * 4/5, :)' vol(n, :)'])

% Create title
title('Box whiskers plot of the volatility');

% Create xlabel
xlabel('Time (* 1/5)');

% Create ylabel
ylabel('Volatility');


% Create textbox
annotation(figure1,'textbox', [0.4 0.01584 0.8 0.03464],...
    'Interpreter','none',...
    'String',{['Samples = ' num2str(samples) '    Alpha = '  num2str(alpha)  '    p = '  num2str(p) ]},...
    'FitBoxToText','off',...
    'LineStyle','none');

if (printFig)
	print(figure1, '-depsc2', ['box_s' num2str(samples) '_a' num2str(alpha) '_p' num2str(p) '.eps']);
end
