function PlotPaths...
   (randstate, samples, Dt, sigma0, S0, xi0, mu, p, alpha, T, ...
      numMethod, printFig)

% Generate the paths.
%[stockAvg, volAvg, xiAvg, stockPaths, volPaths, xiPaths] = NumWrapper...
%   (randstate, samples, Dt, sigma0, S0, xi0, mu, p, alpha, T, ...
%      numMethod);
[stockPaths, volPaths, xiPaths] = stocksim(randstate, samples, Dt, ...
	sigma0, S0, xi0, mu, p, alpha, T, numMethod);

% Create the figure.
CreateStockPlot(0 + Dt : Dt : 1, stockPaths, volPaths, xiPaths, samples, p, alpha, printFig)
CreateStockBoxPlot(0 + Dt : Dt : 1, stockPaths, volPaths, xiPaths, samples, p, alpha, printFig)

